# ========== 站点信息 ==========
title: CVPR-Laboratory
email: wnb_915@163.com
description: 计算机视觉与模式识别实验室 | 三维视觉 · 医疗AI · 多模态学习
baseurl: ""                       # 子路径，自定义域名可留空
url: "https://cvpr-laboratory.github.io"

# ========== 多语言导航栏 ==========
nav:
  - name:
      zh: 首页
      en: Home
    link: /
  - name:
      zh: 关于我们
      en: About
    link: /about/
  - name:
      zh: 团队成员
    link: /team/
  - name:
      zh: 研究方向
      en: Research
    link: /research/
  - name:
      zh: 研究成果
      en: Publications
    link: /publication/
  - name:
      zh: 新闻动态
      en: News
    link: /news/
  - name:
      zh: 合作交流
      en: Collaboration
    link: /collaboration/
  - name:
      zh: 联系我们
      en: Contact
    link: /contact/

# ========== Sass 静默 & 压缩 ==========
sass:
  quiet_deps: true
  style: compressed

defaults:
  - scope:
      path: "_pages"
      type: "pages"          # 小写复数
    values:
      layout: "page"